#!/bin/env zsh

current_version=$(jq -r '.version' widget.json)
IFS='.' read -r major minor patch <<< "$current_version"
((patch++))
new_version="${major}.${minor}.${patch}"
sed -i "s/\"version\": \"$current_version\"/\"version\": \"$new_version\"/" widget.json
git add -A
git commit -m "auto"
git tag ${new_version}
git push gitee ${new_version}
git push origin ${new_version}
git push origin
git push gitee
